version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=$REPOSITORY_URI
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo using VARIABLES
      - echo REPOSITORY_URI = $REPOSITORY_URI
      - echo NODE_ENV = $NODE_ENV
      - echo STAGE = $STAGE
      - echo DOMAIN = $DOMAIN

      - docker build --build-arg NODE_ENV=$NODE_ENV --build-arg STAGE=$STAGE --build-arg DOMAIN=$DOMAIN -t ida-website:$STAGE .
      - docker tag ida-website:$STAGE $REPOSITORY_URI:$STAGE
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPOSITORY_URI:$STAGE
      - echo Changing the Dockerrun file to the correct for this environment
      - sed -i 's/DUMMY_ENV/'$STAGE'/g' Dockerrun.aws.json
artifacts:
  files:
    - Dockerrun.aws.json
    - .ebextensions/*
    