version: 0.2

phases:
  pre_build:
    commands:
      - echo Initalling source NPM depencies
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Using variables
      - echo REPOSITORY_URI = $REPOSITORY_URI
      - echo NODE_ENV = $NODE_ENV
      - echo STAGE = $STAGE
      - echo DOMAIN = $DOMAIN
      - npm run-script build

    post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - .next/**/*
    - public/**/*
    - node_modules/**/*
